### ISSUE TITLE
Subscription: New Command

### ISSUE THREAD

**Issue by ramilexe** [vulcanize/eth-contract-watcher#8]
Create new `cobra.Command` `subscribe`

**Comment by i-norden** [comment]
Keep in mind that the current subscription interface for ipfs-blockchain-watcher needs to be improved. We need to make the subscription completely independent from the sync process, right now it depends on channeling in to the sync process (followed the pattern of how eth rpc subscriptions subscribe to chain events on the core.Blockchain sync process). The subscription server should instead watch insert events in Postgres. This doesn't necessarily need to break the current interface but there are other breaking changes that need to be done (e.g. don't rlp.Encode subscription params).

**Comment by i-norden** [comment]
See https://github.com/vulcanize/contract-watcher-js
